services:
  checker:
    container_name: checker
    platform: linux/arm64 
    build:
      context: ./checker
      dockerfile: Dockerfile
    volumes:
      # - ./checker:/app  # Mount current directory for local development
      - uv-cache:/root/.cache/uv  # Cache UV packages
      - ./database:/app/src/database  # Mount database module
      - ./static:/app/src/static  # Mount static folder
      - ./shared:/app/src/shared  # Add shared utilities
      - ./logs:/logs         # Add logs volume

    environment:
      - PYTHONUNBUFFERED=1  # Ensures Python output is sent straight to terminal
      - TZ=America/Chicago
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://admin:root@postgres:5432/casa_data_portal

    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./checker
          target: /app
        - action: rebuild
          path: ./checker/pyproject.toml

  uploader:
    container_name: uploader
    platform: linux/arm64 
    build:
      context: ./uploader
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
      - ./shared:/app/src/shared
      - ./database:/app/src/database
      - ./config:/app/src/config
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Chicago
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://admin:root@postgres:5432/casa_data_portal
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./uploader
          target: /app
        - action: sync
          path: ./uploader/src
          target: /app/src
        - action: rebuild
          path: ./uploader/pyproject.toml

  api:
    container_name: api
    platform: linux/arm64 
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
      - ./shared:/app/src/shared
      - ./database:/app/src/database
      - ./config:/app/src/config
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Chicago
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://admin:root@postgres:5432/casa_data_portal
    networks:
      - app-network
    ports:
      - "8000:80"  # Map port 8000 to 80
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
        - action: sync
          path: ./api/src
          target: /app/src
        - action: rebuild
          path: ./api/pyproject.toml

  mapper:
    container_name: mapper
    platform: linux/arm64 
    build:
      context: ./mapper
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
      - ./shared:/app/src/shared
      - ./database:/app/src/database
      - ./config:/app/src/config
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Chicago
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://admin:root@postgres:5432/casa_data_portal
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./mapper
          target: /app
        - action: sync
          path: ./mapper/src
          target: /app/src
        - action: rebuild
          path: ./mapper/pyproject.toml

  kerchunker:
    container_name: kerchunker
    build:
      context: ./kerchunker
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
      - ./shared:/app/src/shared
      - ./database:/app/src/database
      - ./config:/app/src/config

    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Chicago
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://admin:root@postgres:5432/casa_data_portal
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./kerchunker
          target: /app
        - action: sync
          path: ./kerchunker/src
          target: /app/src
        - action: rebuild
          path: ./kerchunker/pyproject.toml

  postgres:
    container_name: container-pg
    image: postgres:17.2-alpine
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: casa_data_portal
      TZ: America/Chicago
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d casa_data_portal"]
      interval: 5s
      timeout: 5s
      retries: 5

    develop:
      watch:
        - action: sync
          path: ./config
          target: /docker-entrypoint-initdb.d

  db-init:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: db-initializer
    environment:
      DATABASE_URL: "postgresql+asyncpg://admin:root@postgres:5432/casa_data_portal"
      TZ: America/Chicago
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 10s
      timeout: 5s
      retries: 5

    develop:
      watch:
        - action: rebuild
          path: ./database
          target: /app

volumes:
  uv-cache:  # Persistent cache for UV packages
  postgres-data:
  logs:
    driver: local

networks:
  app-network:
